config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users
  resources :questions

  get 'show' => 'users#show'

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :user
  validates :text, :user, presence: true

  validates :text, length: {maximum: 255}

end

app/models/user.rb
require 'openssl'

class User < ActiveRecord::Base
  # Параметры работы модуля шифрования паролей
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions

  validates :email, :username, presence: true
  validates :email, :username, uniqueness: true

  # Email validations
  validates_email_format_of :email, :message => 'incorrect email'

  # Username validations
  validates :username, length: { maximum: 40 }
  validates :username, format: { with: /\A[a-zA-Z0-9_]+\z/ }

  # Password validations
  validates :password, length: {
      minimum: 8,
      maximum: 20
  }

  attr_accessor :password

  validates_presence_of :password, on: :create
  validates_confirmation_of :password

  before_save :encrypt_password

  before_validation :downcase_fields

  def downcase_fields
    self.username.downcase!
  end

  def encrypt_password
    if self.password.present?
      # создаем соль
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      # создаем хэш пароля
      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
    end
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email) # Находим пользователя по email

    if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = [
        User.new(
            id: 1,
            name: 'Rinat',
            username: 'ChesterLife',
            avatar_url: 'https://s.gravatar.com/avatar/f109a9b2cb97061cbb2fb843e1bd2f5a?s=100'
        ),
        User.new(
            id: 2,
            name: 'John',
            username: 'SuperJohn'
        )
    ]
  end

  def new
  end

  def edit
  end

  def show
    @user = User.new(
            name: 'Rinat',
            username: 'ChesterLife',
            avatar_url: 'https://s.gravatar.com/avatar/f109a9b2cb97061cbb2fb843e1bd2f5a?s=100'
    )

    @questions = [
      Question.new(text: 'How are you?', created_at: Date.parse('27.03.2016')),
      Question.new(text: 'What you do?', created_at: Date.parse('27.03.2016'))
    ]

    @new_question = Question.new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.jpg'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>Good questions</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="header">
    <div class="container">
      <div class="header-logo">
        <h1 class="header-title"><%= link_to 'Good questions', root_path %></h1>
      </div>
    </div>
  </div>

  <div class="content">
    <div class="container">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
    <%= question.text %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer if question.answer.present? %>
      </div>
    <% end %>

    <div class="question-date">
      <%= question.created_at.strftime('%d %b %M:%H') %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
     <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%#В шаблоне show мы пишем html-код для вывода внутреннго содержимого страницы пользователя%>

<%#Блок с информацией о пользователей%>
<div class="user-header text-center">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="user-image-div">
    <%#Мы используем хелперы image_tag (встроенный в rails) и наш user_avatar%>
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[avatar]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>

  <div class="user-ask-button container text-center">
    <%#Используем встроенный в rails хелпер link_to%>
    <%= link_to 'Спроси меня', '', class: 'button button-light', id: 'ask-button' %>
  </div>
</div>

<%#Блок с формой для задавания пользователю вопроса%>
<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <div class="form">
      <%#Мы используем хелпер form_for, принимающий на вход блок erb-кода, в котором доступна%>
      <%#переменная f, содержащая так называемый form builder, с помощью которого можно делать%>
      <%#поля формы для нового вопроса%>
      <%= form_for @new_question do |f| %>
          <%#С помощью объекта для создания полей формы, связанной с моделью @new_question%>
          <%#Мы создаем инпуты с нужными полями для формы, значения будут подставлены rails%>
          <%#автоматически%>
          <%= f.hidden_field :user_id %>

          <div class="form-field">
            <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
            <%= f.text_area :text, class: 'form-textarea' %>
          </div>

          <div class="form-action">
            <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

<%#Блок со списком вопросов к пользователю%>
<div class="column-3-4">
  <div class="user-questions buffer-both">
<<<<<<< HEAD

    <div class="user-statistics">
      <%= "У Вас #{@questions.count.to_s} вопроса" %>
    </div>  

=======
>>>>>>> fe9e2f55b8c4754861c077d5385ea0f5fc82e811
    <div class="questions-list">
      <%#Обратите внимание, как мы делаем цикл по всем вопросам,%>
      <%#точно также, как мы делали циклы в ruby%>
      <% @questions.each do |question| %>
          <%#Мы рисуем здесь для кажого вопроса в списке вопросов%>
          <%#фрагмент (паршал), передавая в него текущий вопрос%>
          <%#Это очень похоже на вызов метода в ruby%>
          <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>